//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVENTORY
    {
        public string ID_INVENTORY { get; set; }
        public string ELECTRONICA_INVENTORY { get; set; }
        public string MUEBLES_INVENTORY { get; set; }
        public string LINEABLANCA__INVENTORY { get; set; }
    }
}
