/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package robinsonbravo;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Batto
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public FormularioPrincipal() {
        initComponents();
        this.cliList = new ArrayList<Cliente>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1IdCliente = new javax.swing.JTextField();
        jLabel3IdCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2Cargo = new javax.swing.JTextField();
        jLabel5Cargo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3Ciudad = new javax.swing.JTextField();
        jLabel7Ciudad = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9Tarjetas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11Apellido = new javax.swing.JLabel();
        jTextField5Rut = new javax.swing.JTextField();
        jTextField6Nombre = new javax.swing.JTextField();
        jTextField7Apellido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8FechaNacimiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14FechaNacimiento = new javax.swing.JLabel();
        jLabel15Rut = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18Nombre = new javax.swing.JLabel();
        jLabel19Sexo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22EstadoCivil = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jComboBox1EstadoCivil = new javax.swing.JComboBox<>();
        jComboBox1Seco = new javax.swing.JComboBox<>();
        jComboBox1Tarjetas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5NombreClienteMayor = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setText("ID Cliente:");

        jLabel4.setText("Cargo:");

        jLabel6.setText("Ciudad:");

        jLabel8.setText("Tarjeta que Posee:");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Apellido:");

        jTextField5Rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5RutActionPerformed(evt);
            }
        });

        jLabel12.setText("Fecha Nacimiento:");
        jLabel12.setToolTipText("");

        jLabel13.setText("Rut :");

        jLabel16.setText("Sexo:");

        jLabel17.setText("Nombre :");

        jLabel20.setText("Estado Civil:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Rut", "Nombre", "Apellido", "Fecha de Nacimiento", "Edad", "Estado Civil", "Sexo", "ID Cliente", "Cargo", "Ciudad", "Tarjeta que Posee"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Limpiar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Seleccione >>", "Soltero", "Casado", "Viudo", "Divorciado" }));

        jComboBox1Seco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Seleccione >>", "M", "F" }));

        jComboBox1Tarjetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Seleccione >>", "Cuenta Rut", "Cuenta Corriente", "Cuenta de Ahorro", "Chequera Electronica", "Tarjeta de Credito", "Cuenta Vista", "Visa", "Mastercard" }));

        jLabel3.setText("El Cliente con mayor edad es:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5NombreClienteMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(344, 344, 344))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15Rut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField5Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel11Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jTextField7Apellido))))
                                        .addGap(192, 192, 192)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                    .addComponent(jLabel7Ciudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextField3Ciudad)
                                                    .addComponent(jLabel3IdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextField1IdCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(192, 192, 192)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jComboBox1Seco, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel19Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1Tarjetas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel18Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField8FechaNacimiento)
                                    .addComponent(jLabel14FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22EstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2Cargo)
                                    .addComponent(jLabel5Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9Tarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextField6Nombre, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField5Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField7Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1Seco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel19Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTextField6Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField8FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel22EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1Tarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9Tarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5NombreClienteMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!validarCamposObligatorios()) {
            // Datos del cliente. 
            Cliente cli = new Cliente();
            cli.setIdCliente(Integer.parseInt(jTextField1IdCliente.getText()));
            cli.setCargo(Integer.parseInt(jTextField2Cargo.getText()));
            cli.setCiudad(jTextField3Ciudad.getText());
            cli.setTarjetasQuePosee(this.jComboBox1Tarjetas.getSelectedItem().toString());
            // Datos de la persona.
            Date dt = new Date(jTextField8FechaNacimiento.getText());
            cli.setRut(jTextField5Rut.getText());
            cli.setNombre(jTextField6Nombre.getText());
            cli.setApellido(jTextField7Apellido.getText());
            cli.setFecha_nacimiento(dt);
            cli.setEstadoCivil(this.jComboBox1EstadoCivil.getSelectedItem().toString());
            cli.setSexo(this.jComboBox1Seco.getSelectedItem().toString());
            cli.calcularEdad(jTextField8FechaNacimiento.getText());
            cliList.add(cli);
            this.clienteMayorEdad();
            this.jTable2.setModel(new DefaultTableModel(null, new String[]{
                "Nro", "Rut", "Nombre", "Apellido", "Fecha de Nacimiento", "Edad", "Estado Civil", "Sexo", "ID Cliente", "Cargo", "Ciudad", "Tarjeta que Posee"
            }));
            for (int i = 0; i < cliList.size(); i++) {
                DefaultTableModel model = (DefaultTableModel) this.jTable2.getModel();

                model.addRow(new Object[]{
                    i + 1,
                    cliList.get(i).getRut(),
                    cliList.get(i).getNombre(),
                    cliList.get(i).getApellido(),
                    cliList.get(i).getFecha_nacimiento(),
                    cliList.get(i).getEdad(),
                    cliList.get(i).getEstadoCivil(),
                    cliList.get(i).getSexo(),
                    cliList.get(i).getIdCliente(),
                    cliList.get(i).getCargo(),
                    cliList.get(i).getCiudad(),
                    cliList.get(i).getTarjetasQuePosee()
                });
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.jLabel15Rut.setText("");
        this.jLabel18Nombre.setText("");
        this.jLabel11Apellido.setText("");
        this.jLabel14FechaNacimiento.setText("");
        this.jLabel19Sexo.setText("");
        this.jLabel22EstadoCivil.setText("");
        this.jLabel3IdCliente.setText("");
        this.jLabel5Cargo.setText("");
        this.jLabel7Ciudad.setText("");
        this.jLabel9Tarjetas.setText("");
        this.jTextField5Rut.setText("");
        this.jTextField6Nombre.setText("");
        this.jTextField7Apellido.setText("");
        this.jTextField8FechaNacimiento.setText("");
        this.jTextField1IdCliente.setText("");
        this.jTextField2Cargo.setText("");
        this.jTextField3Ciudad.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5RutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5RutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5RutActionPerformed

    public boolean validarCamposObligatorios() {
        this.jLabel15Rut.setText("");
        this.jLabel18Nombre.setText("");
        this.jLabel11Apellido.setText("");
        this.jLabel14FechaNacimiento.setText("");
        this.jLabel19Sexo.setText("");
        this.jLabel22EstadoCivil.setText("");
        this.jLabel3IdCliente.setText("");
        this.jLabel5Cargo.setText("");
        this.jLabel7Ciudad.setText("");
        this.jLabel9Tarjetas.setText("");

        this.jTextField5Rut.setText(jTextField5Rut.getText().trim());
        this.jTextField6Nombre.setText(jTextField6Nombre.getText().trim());
        this.jTextField7Apellido.setText(jTextField7Apellido.getText().trim());
        this.jTextField8FechaNacimiento.setText(jTextField8FechaNacimiento.getText().trim());
        this.jTextField1IdCliente.setText(jTextField1IdCliente.getText().trim());
        this.jTextField2Cargo.setText(jTextField2Cargo.getText().trim());
        this.jTextField3Ciudad.setText(jTextField3Ciudad.getText().trim());

        boolean errRut = false;
        boolean errNombre = false;
        boolean errApellido = false;
        boolean errFechadeNacimiento = false;
        boolean errEstadoCivil = false;
        boolean errSexo = false;
        boolean errIDCliente = false;
        boolean errCargo = false;
        boolean errCiudad = false;
        boolean errTarjetaqueposee = false;

        // Rut
        if ("".equals(this.jTextField5Rut.getText().trim())) {
            this.jLabel15Rut.setText("Campo Obligatorio.");
            errRut = true;
        } else {
            try {
                Double num = Double.parseDouble(this.jTextField5Rut.getText().trim());
            } catch (NumberFormatException e) {
                this.jLabel15Rut.setText("Debe ser un número.");
                errRut = true;
            }
        }

        // Nombre
        if ("".equals(this.jTextField6Nombre.getText().trim())) {
            this.jLabel18Nombre.setText("Campo Obligatorio.");
            errNombre = true;
        }

        // Apellido
        if ("".equals(this.jTextField7Apellido.getText().trim())) {
            this.jLabel11Apellido.setText("Campo Obligatorio.");
            errApellido = true;
        }

        // FechadeNacimiento
        if ("".equals(this.jTextField8FechaNacimiento.getText().trim())) {
            this.jLabel14FechaNacimiento.setText("Campo Obligatorio.");
            errFechadeNacimiento = true;
        }

        // Sexo
        if ("<< Seleccione >>".equals(this.jComboBox1Seco.getSelectedItem().toString())) {
            this.jLabel19Sexo.setText("Campo Obligatorio.");
            errEstadoCivil = true;
        }

        // EstadoCivil
        if ("<< Seleccione >>".equals(this.jComboBox1EstadoCivil.getSelectedItem().toString())) {
            this.jLabel22EstadoCivil.setText("Campo Obligatorio.");
            errSexo = true;
        }

        // IDCliente
        if ("".equals(this.jTextField1IdCliente.getText().trim())) {
            this.jLabel3IdCliente.setText("Campo Obligatorio.");
            errIDCliente = true;
        } else {
            try {
                Double num = Double.parseDouble(this.jTextField1IdCliente.getText().trim());
            } catch (NumberFormatException e) {
                this.jLabel3IdCliente.setText("Debe ser un número.");
                errIDCliente = true;
            }
        }

        // Cargo
        if ("".equals(this.jTextField2Cargo.getText().trim())) {
            this.jLabel5Cargo.setText("Campo Obligatorio.");
            errCargo = true;
        } else {
            try {
                Double num = Double.parseDouble(this.jTextField2Cargo.getText().trim());
            } catch (NumberFormatException e) {
                this.jLabel5Cargo.setText("Debe ser un número.");
                errCargo = true;
            }
        }

        // Ciudad
        if ("".equals(this.jTextField3Ciudad.getText().trim())) {
            this.jLabel7Ciudad.setText("Campo Obligatorio.");
            errCiudad = true;
        }

        // Tarjetaqueposee
        if ("<< Seleccione >>".equals(this.jComboBox1Tarjetas.getSelectedItem().toString())) {
            this.jLabel9Tarjetas.setText("Campo Obligatorio.");
            errTarjetaqueposee = true;
        }

        return errRut || errNombre || errApellido || errFechadeNacimiento || errEstadoCivil || errSexo || errIDCliente || errCargo || errCiudad || errTarjetaqueposee;
    }

    public void clienteMayorEdad() {
        String nombremayorEdad = "";
        int edad = 0;
        int indexEdad = 0;
        this.jLabel5NombreClienteMayor.setText("");
        edad = cliList.get(0).getEdad();
        for (int i = 1; i < cliList.size(); i++) {
            if (edad < cliList.get(i).getEdad()) {
                edad = cliList.get(0).getEdad();
                indexEdad = i;
            }
        }
        nombremayorEdad = cliList.get(indexEdad).getNombre() + "" + cliList.get(indexEdad).getApellido();
        this.jLabel5NombreClienteMayor.setText(nombremayorEdad);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    private ArrayList<Cliente> cliList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1EstadoCivil;
    private javax.swing.JComboBox<String> jComboBox1Seco;
    private javax.swing.JComboBox<String> jComboBox1Tarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11Apellido;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14FechaNacimiento;
    private javax.swing.JLabel jLabel15Rut;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18Nombre;
    private javax.swing.JLabel jLabel19Sexo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22EstadoCivil;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3IdCliente;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5Cargo;
    private javax.swing.JLabel jLabel5NombreClienteMayor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7Ciudad;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9Tarjetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1IdCliente;
    private javax.swing.JTextField jTextField2Cargo;
    private javax.swing.JTextField jTextField3Ciudad;
    private javax.swing.JTextField jTextField5Rut;
    private javax.swing.JTextField jTextField6Nombre;
    private javax.swing.JTextField jTextField7Apellido;
    private javax.swing.JTextField jTextField8FechaNacimiento;
    // End of variables declaration//GEN-END:variables
}
