
use database BD_INVENTORY_LIST;

-- DROP table dbo.TBL_INVENTORY;

create table dbo.TBL_INVENTORY (
	ID_INVENTORY INT NOT NULL,
	ELECTRONICA_INVENTORY varchar(20) NOT NULL,
	MUEBLES_INVENTORY varchar(20) NOT NULL,
	LINEABLANCA_INVENTORY varchar(20) NOT NULL,
	CONSTRAINT TBL_INVENTORY_pk PRIMARY KEY (ID_INVENTORY),
);
