//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTareasDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONTACT
    {
        public int idContactList { get; set; }
        public string NameContact { get; set; }
        public string PhoneContact { get; set; }
        public string EmailContact { get; set; }
        public string AddressContact { get; set; }
    }
}
