//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTareasDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONTACT
    {
        public int ID_CONTACT { get; set; }
        public string NAME_CONTACT { get; set; }
        public string ADDRESS_CONTACT { get; set; }
        public string PHONE_CONTACT { get; set; }
        public string MAIL_CONTACT { get; set; }
    }
}
